linters:
  enable:
    # https://github.com/golangci/golangci-lint#enabled-by-default-linters
    # additional linter you want to activate may be specified here...
    - golint # official golang linter
    # https://github.com/maratori/testpackage
    # used to enforce blackbox testing
    - testpackage
    # https://github.com/securego/gosec
    # inspects source code for security problems by scanning the Go AST.
    - gosec
issues:
  exclude-rules:
    # Exclude gosec from running on tests files.
    - path: _test\.go
      linters:
        - gosec
    # Exclude gosec from our internal/test pkg
    - path: internal/test
      linters:
        - gosec