run:
  # also lint files within /scripts. Those have "//go:build scripts" set.
  build-tags:
    - scripts
linters:
  enable:
    # https://github.com/golangci/golangci-lint#enabled-by-default-linters
    # Additional linters you want to activate may be specified here...

    # ---
    # https://github.com/mgechev/revive
    # replacement for the now deprecated official golint linter, see https://github.com/golang/go/issues/38968
    - revive

    # ---
    # https://github.com/maratori/testpackage
    # used to enforce blackbox testing
    - testpackage

    # ---
    # https://github.com/securego/gosec
    # inspects source code for security problems by scanning the Go AST.
    - gosec

    # ---
    # https://github.com/ultimatepate/usetesting
    # detects when some calls can be replaced by methods from the testing package.
    - usetesting

    # ---
    # https://github.com/polyfloyd/go-errorlint
    # ensure we are comparing errors via errors.Is, types/values via errors.As and wrap errors with %w.
    - errorlint
