# This is our base swagger file and the primary mixin target.
# Everything in definitions|paths/*.yml will be mixed through
# and finally flattened into the actual swagger.yml in this dir.
consumes:
  - application/json
produces:
  - application/json
swagger: "2.0"
info:
  title: allaboutapps.dev/aw/go-starter
  version: 0.1.0
  description: API documentation
paths: {}
definitions:
  orderDir:
    type: string
    enum:
      - asc
      - desc
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
    description: |-
      Access token for application access, **must** include "Bearer " prefix.
      Example: `Bearer b4a94a42-3ea2-4af3-9699-8bcbfee6e6d2`
    x-keyPrefix: "Bearer "
  Management:
    type: apiKey
    in: query
    description: Management secret, used for monitoring and infrastructure related calls
    name: mgmt-secret
