// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// SomeSampleType SomeSampleType some sample type
//
// swagger:model SomeSampleType
type SomeSampleType struct {

	// data
	// Required: true
	// Min Length: 5
	Data *string `json:"data"`

	// Id
	// Required: true
	ID *string `json:"id"`

	// moreData
	// Required: true
	MoreData *string `json:"moreData"`
}

// Validate validates this some sample type
func (m *SomeSampleType) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateData(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMoreData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SomeSampleType) validateData(formats strfmt.Registry) error {

	if err := validate.Required("data", "body", m.Data); err != nil {
		return err
	}

	if err := validate.MinLength("data", "body", string(*m.Data), 5); err != nil {
		return err
	}

	return nil
}

func (m *SomeSampleType) validateID(formats strfmt.Registry) error {

	if err := validate.Required("id", "body", m.ID); err != nil {
		return err
	}

	return nil
}

func (m *SomeSampleType) validateMoreData(formats strfmt.Registry) error {

	if err := validate.Required("moreData", "body", m.MoreData); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *SomeSampleType) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SomeSampleType) UnmarshalBinary(b []byte) error {
	var res SomeSampleType
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
